name: OpenAPI

on:
  pull_request:

concurrency:
  group: openapi-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  openapi:
    runs-on: ubuntu-latest

    if: ${{ github.repository_owner != 'nextcloud-gmbh' }}

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: apcu,ctype,curl,dom,fileinfo,ftp,gd,intl,json,ldap,mbstring,openssl,pdo_sqlite,posix,sqlite,xml,zip
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Composer install
        run: composer i

      - name: OpenAPI checker
        run: build/openapi-checker.sh
